### ISSUE TITLE
Missing footer links and cookie consent

### ISSUE THREAD

**Issue by oliviergoulet5** [eclipse-sdv-blueprints/blueprints-website#5]
Hi! 

I received a request to link this website to the [Eclipse SDV Blueprints project page](https://projects.eclipse.org/projects/automotive.sdv-blueprints) on projects.eclipse.org. While doing so, I noticed some links were missing from your footer:

1) Main Eclipse Foundation website (https://www.eclipse.org)
2) Privacy policy (https://www.eclipse.org/legal/privacy.php)
3) Website terms of use (https://www.eclipse.org/legal/termsofuse.php)
4) Copyright agent (https://www.eclipse.org/legal/copyright.php)
5) Legal (https://www.eclipse.org/legal)

The full policy can be read here: https://www.eclipse.org/org/documents/eclipse-foundation-hosted-services-privacy-and-acceptable-usage-policy.pdf

Please let me know if you have any questions. Thanks!

**Comment by nacidai** [comment]
Added the missing links.

**Comment by nacidai** [comment]
Our website does not use cookies. Please see the result

https://www.cookieserve.com/scan-summary/?url=https%3A%2F%2Fsdv-blueprints.eclipse.dev%2F

![Screenshot 2024-11-26 at 14 03 16](https://github.com/user-attachments/assets/2829574f-0100-4df2-9b6e-97346c044e73)

**Comment by oliviergoulet5** [comment]
Awesome. Thanks @nacidai !
